name: 'Terraform Apply (Build)'

on:
  workflow_dispatch: # This adds the "Run workflow" button

permissions:
  id-token: write
  contents: read

jobs:
  terraform_apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.5"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          TF_VAR_openai_api_key: ${{ secrets.TF_VAR_OPENAI_API_KEY }}
          TF_VAR_pinecone_api_key: ${{ secrets.TF_VAR_PINECONE_API_KEY }}
        run: terraform apply -auto-approve -var-file="config.tfvars"
